/*
 * @Author: YPL
 * @Date: 2022-08-02 16:33:45
 * @Description: 
 */
package exception;

public class ExceptionTest {
    public static void main(String[] args) {
        
        int res1 = 25/0;
        System.out.println(res1);
        
        
        // try {
        //     int res = 25 / 0;
        //     System.out.println(res);
        // } catch (Exception e) {
        //    System.out.println(e.getCause());
        //    System.out.println(e.getMessage());
        //     e.printStackTrace();
        // }

    }
}
